//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDownBandingMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StatedId { get; set; }
    
        public virtual States States { get; set; }
    }
}
